version: "3"
services:
  #------------------------------------------------------------------------------
  mempool_recorder_mongo2:
    image: mongo:latest
    container_name: mempool_recorder_mongo2
    ##    ports:
    ##      - "27017:27017"
    networks:
      bitnet:
        ipv4_address: ${MEMPOOL_RECORDER_MONGO2_IP_ADDRESS}
    volumes:
      - mempool_recorder_mongo_volume2:/data/db
    restart: always
#------------------------------------------------------------------------------
volumes:
  mempool_recorder_mongo_volume2:

#------------------------------------------------------------------------------
networks:
  bitnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
#        - gateway: 172.18.0.1
